### PR TITLE
update peer dependency for svelte 4

### PR DESCRIPTION
**Pull request by saadeghi**

### CODE REVIEW

**Comment by vnphanquang** [comment]
@saadeghi thank you. Sorry, update to support Svelte 4 is in my todo list but I'm too caught up with work currently. Will do soon

**Comment by saadeghi** [comment]
@vnphanquang Looks like everything works fine already. The package works with Svelte 4 but I need to use `--legacy-peer-deps` flag everytime because of the peer dependency

**Comment by vnphanquang** [comment]
Yeah, that's expected, and annoying for sure. I'm planning to align migration to vanilla JS with the next release. But perhaps i should hold that off and do a patch for Svelte peer dependency update.

**Comment by brandonp-ais** [comment]
> I'm planning to align migration to vanilla JS with the next release. 

Like svelte/kit? That'd be cool.

**Review by vnphanquang — APPROVED** [review]

**Comment by vnphanquang** [comment]
@brandonp-ais yes, svelte team really opens up my mind about the benefits of vanilla JS, and they align very well with svelte-put packages

**Comment by vnphanquang** [comment]
Note: added same peer dependency re-config to all packages; added changeset

**Pull request merged**
